### ISSUE TITLE
Missing required key 'RouteKey' in params

### ISSUE THREAD

**Issue by wkimdev** [wkimdev/hello-serverless#2]
- 아래 처럼 deploy를 잘하다가 에러가 발생 

  
```
>sls deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service hello-serverless.zip file to S3 (11.84 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.........................................................................................
Serverless: Stack update finished...
Service Information
service: hello-serverless
stage: dev
region: ap-northeast-2
stack: hello-serverless-dev
resources: 25
api keys:
  None
endpoints:
  wss://8gtimpq2ge.execute-api.ap-northeast-2.amazonaws.com/dev
functions:
  connectionHandler: hello-serverless-dev-connectionHandler
  defaultHandler: hello-serverless-dev-defaultHandler
  sendMessageHandler: hello-serverless-dev-sendMessageHandler
layers:
  None
Serverless: Deploying Websockets API named "hello-serverless-dev-websockets-api"...

  Serverless Error ---------------------------------------

  Missing required key 'RouteKey' in params
```
- serverless.yml의 plugin설정을 지우니 해결됨! (plugin설정 안해도 사용할 수 있도록 업데이트 되었다고 함)
